### ISSUE TITLE
Add support for private static IPs managed by BOSH

### ISSUE THREAD

**Issue by keymon** [frodenas/bosh-google-cpi#1]
It would be interesting to support private static IPs for some scenarios. 

GCE VMs don't support this feature out of the box, but I think it could be possible to leverage [this hack documented by Google itself](https://cloud.google.com/compute/docs/instances-and-network?hl=en#staticnetworkaddress) to achieve it:

> Although Compute Engine does not allow you to create an instance with a specific network IP address, you can use a combination of routes and an instance's --can-ip-forward ability to add an IP address as a static network IP address that then maps to your desired virtual machine instance.
>
> For example, if you want to assign 10.1.1.1 specifically as a network IP address to a virtual machine instance, you can create a static route that sends traffic from 10.1.1.1 to your instance, even if the instance's network IP address assigned by Compute Engine doesn't match your desired network IP address.

The CPI could create the VM, get the ID and setup the required routing using GCE firewall rules to get a working IP. The required networking conifg in the VM can be set using [a cloud init script](https://cloud.google.com/compute/docs/startupscript?hl=en#provide_a_startup_script_file), using bosh-agent or implementing some logic in the stemcell.

I am not sure if the old IP must be keep, or instead, if it can be drop and all the traffic can be routed using the new IP. Probably the less confusing approach keep dynamic network as required and static as optional.

The main issue with this approach is that breaks the principle of least astonishment, as the VMs use a different address ranges that the ones defined in the IaaS. Also, the new IP won't appear on the GCE console.

**Comment by frodenas** [comment]
@keymon Thanks for you suggestion. This won't be complex to implement, as the bosh agent already configures the network interfaces, but will need lots of testing for failure scenarios. Unfortunately, I'm not actively maintaining this CPI, although any contributions will be very welcomed.

Just to satisfy my curiosity, why do you want to add support for manual networks when GCE doesn't consider them 1st class citizens?

**Comment by keymon** [comment]
In our case deploying CF using [the official cf-release templates](https://github.com/cloudfoundry/cf-release/tree/master/templates) is an issue because services like etcd, consul or NFS need static IPs. 

But a lot of manifests and bosh releases assume static IPs, as all the other CPIs support it.

So far [we solved it with BOSH powerdns](https://github.com/alphagov/cf-terraform/blob/normalise_manifests/manifests/templates/gce/cf-infrastructure-gce.yml#L15-L17) and it is true that can be workaround using `vip` with public static IPs.

**Comment by frodenas** [comment]
Understood, makes sense, thanks for the explanation.

**Comment by frodenas** [comment]
Closing this as this repo is no longer maintained. Support for `manual` networks is going to be added at the official [bosh-google-cpi-release](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release) release.
